# Generated by Django 5.2.5 on 2025-08-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0003_useractivity_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_view_customer_list', 'Can view the list of all customers'), ('can_deactivate_user', 'Can deactivate a user account'), ('can_promote_to_staff', 'Can assign a user to the Staff role'), ('can_manage_vendors', 'Can manage vendor accounts')]},
        ),
        migrations.AddField(
            model_name='customuser',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='products.product'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Optional. You can add a profile picture later.', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STAFF', 'Staff'), ('CUSTOMER', 'Customer'), ('VENDOR', 'Vendor')], default='CUSTOMER', max_length=50),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('PURCHASE', 'Made a Purchase'), ('WISHLIST_ADD', 'Added to Wishlist')], max_length=100),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['timestamp'], name='users_usera_timesta_6dbdeb_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['action'], name='users_usera_action_acb2ad_idx'),
        ),
    ]
