# Generated by Django 5.2.5 on 2025-08-26 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_options_customuser_favorites_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
